services:
  - type: web
    name: admission-system
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && python download_nltk_data.py"
    startCommand: "gunicorn backend.app:app --workers 4 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: USE_RAG_CHATBOT
        value: false
      - key: LLM_PROVIDER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: admission-db
          property: connectionString
    
  - type: pserv
    name: admission-db
    env: postgres
    region: singapore
    plan: free
    ipAllowList: []
